### PR TITLE
[Compute AG: WAAS] Split the OOB pages for container and host

### PR DESCRIPTION
**Pull request by divyabhushan-okta**
## Reference
Discussion on the ticket [here](https://redlock.atlassian.net/browse/CWP-46059).

## Staged content
[Deploy WAAS Out-of-Band for Containers](https://stage.docs.paloaltonetworks.com/prisma/prisma-cloud/22-12/prisma-cloud-compute-edition-admin/waas/deploy_waas/deploy_oob_containers)

[Deploy WAAS Out-of-Band for Hosts](https://stage.docs.paloaltonetworks.com/prisma/prisma-cloud/22-12/prisma-cloud-compute-edition-admin/waas/deploy_waas/deploy_oob_hosts)

### CODE REVIEW

**Comment by divyabhushan-okta** [comment]
@Pubs-MV The file `compute/admin_guide/waas/deploy_waas/deployment_out_of_band.adoc` has to be deleted as it's now split into `deploy_oob_containers.adoc` and `deploy_oob_hosts.adoc`.

**Comment by Pubs-MV** [comment]
What will happen if someone accesses the link for compute/admin_guide/waas/deploy_waas/deployment_out_of_band.adoc?
I saw your ticket for the in-app (?), is that the only impact?

**Comment by divyabhushan-okta** [comment]
@Pubs-MV This page `compute/admin_guide/waas/deploy_waas/deployment_out_of_band.adoc` will no longer exists and will not have any xrefs references to it. Not even from the UI.
Any older reference to this file, such as from the `22.12` RN should be redirected to `https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-12/prisma-cloud-compute-edition-admin/waas/waas-intro#_waas_out_of_band` for PCCE, and `https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/waas/waas-intro#_waas_out_of_band` for PCEE.

**Comment by Pubs-MV** [comment]
@iansk please resolve the conflict to merge this PR for the publish

**Pull request merged**
