### PR TITLE
Update licensing.adoc

### PR DESCRIPTION
**Pull request by Pubs-MV**
added an update to state that twistcli does not consume credits

### CODE REVIEW

**Comment by Pubs-MV** [comment]
hey @Aqsaxvv092, should this page be updated for agentless scan?

**Comment by Aqsaxvv092** [comment]
@Pubs-MV done.

**Comment by Pubs-MV** [comment]
> @Pubs-MV done.

thank you, @Aqsaxvv092

**Comment by Pubs-MV** [comment]
Hello @iansk, please review this change and include it in the updated AG we publish this week.

**Review by iansk — APPROVED** [review]

**Pull request merged**
