### PR TITLE
[Compute API] API issue # 40773 - Remove unsupported endpoints and update missing titles

### PR DESCRIPTION
**Pull request by ssugandh**
- GH# 40773 - Removed the endpoint that downloads the MMDB file from DB Lite database.
- Added titles to the /util endpoints.
- Corrected Defenders serverless cURL example.
- Updated the topic map file.

### CODE REVIEW

**Comment by Pubs-MV** [comment]
@ssugandh , per https://spring.paloaltonetworks.com/twistlock/twistlock/issues/40773, we should unpublish this endpoint. PTAL and let @MayaShani and  me know if you have questions.

**Comment by ssugandh** [comment]
@Pubs-MV : I have removed other unsupported and v1 endpoints also from our topic map.

**Review by Pubs-MV — APPROVED** [review]
please confirm that these endpoints are marked as supported but not b/c, if that was agreed with @MayaShani 

approving to ungate you, @ssugandh

**Comment by ssugandh** [comment]
@Pubs-MV and @iansk : Please see if this can be merged. I don't have the merge permissions.
This will close the issue here: https://spring.paloaltonetworks.com/twistlock/twistlock/issues/40773

**Pull request merged**
