### PR TITLE
Update Kubernetes Defender Installation

### PR DESCRIPTION
**Pull request by rcaballeromx**

### CODE REVIEW

**Comment by Pubs-MV** [comment]
@rcaballeromx , please check with @iansk about the best place to add the cluster-context information. I am not sure that it should be standalone topic under the install defender section.

Also all files that reference install_defender/cluster-context.adoc needs to be fixed. The file name uses"-" but the links go to "_"

**Comment by iansk** [comment]
@rcaballeromx @Pubs-MV 

I think the best place to put the cluster context info is in the [technology_overviews/radar.adoc](https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/compute/admin_guide/technology_overviews/radar.adoc) article. There's already a section there about the cluster "pivot", so you can just update it with whatever's relevant/important from cluster-context.adoc.

**Comment by rcaballeromx** [comment]
Thank you @iansk 
I will probably just include the fragment like it was included before, but do so in [technology_overviews/radar.adoc](https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/compute/admin_guide/technology_overviews/radar.adoc).
If I can quickly trim it to make sure the content is limited to the relevant info, I'll do that too, but I need to take a look before I know for sure.

**Comment by Pubs-MV** [comment]
@rcaballeromx are the changes ready?

**Comment by rcaballeromx** [comment]
@Pubs-MV @iansk I've updated the PR to ensure that the restructured content builds. PTAL

**Review by iansk — APPROVED** [review]
Looks good, thanks @rcaballeromx

**Pull request merged**
