### PR TITLE
Update install_single_container_defender.adoc

### PR DESCRIPTION
**Pull request by snps-aggarw**
console ip address

### CODE REVIEW

**Review by Pubs-MV — APPROVED** [review]
Thank you @snps-aggarw

**Comment by snps-aggarw** [comment]
Hi Sath,

Can you help  me  in figuring out what this notification for?

Best
Priyanka

From: Pubs-MV ***@***.***>
Date: Friday, June 24, 2022 at 8:48 AM
To: PaloAltoNetworks/prisma-cloud-docs ***@***.***>
Cc: Priyanka Aggarwal ***@***.***>, Mention ***@***.***>
Subject: Re: [PaloAltoNetworks/prisma-cloud-docs] Update install_single_container_defender.adoc (PR #371)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@Pubs-MV approved this pull request.

Thank you @snps-aggarw<https://urldefense.com/v3/__https:/github.com/snps-aggarw__;!!A4F2R9G_pg!dajk6vDt-7qCnuTUhnBUT5EpXWHKKn2Qk03rvOtc5ikXEj38hNHOChSk1ZZAmTnF4UJGvbY_17vTaa7vA0B6tdvc$>

**Comment by snps-aggarw** [comment]
Hi Priyanka,

I remember you made an edit request to the public documentation in one of
the calls, which took you to GitHub to submit the request. This must be
related to that.


Thanks,


Sathappan Krishnan  |  Customer Success Manager - Prisma Cloud

Palo Alto Networks  |  3000 Tannery Way  |  Santa Clara, CA 95054  |  USA

Mobile: 925.699.8525  | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>


<https://www.paloaltonetworks.com/prisma>

**Comment by snps-aggarw** [comment]
Gotcha , thanks Sath 😊

From: Sathappan Krishnan ***@***.***>
Date: Friday, June 24, 2022 at 10:09 AM
To: Priyanka Aggarwal ***@***.***>
Cc: PaloAltoNetworks/prisma-cloud-docs ***@***.***>, PaloAltoNetworks/prisma-cloud-docs ***@***.***>, Mention ***@***.***>, Chad Cazzato ***@***.***>, Sudesh Gadewar ***@***.***>, Vamsi Krishna Muttireddy ***@***.***>
Subject: Re: [PaloAltoNetworks/prisma-cloud-docs] Update install_single_container_defender.adoc (PR #371)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi Priyanka,

I remember you made an edit request to the public documentation in one of the calls, which took you to GitHub to submit the request. This must be related to that.



Thanks,



Sathappan Krishnan  |  Customer Success Manager - Prisma Cloud

Palo Alto Networks  |  3000 Tannery Way  |  Santa Clara, CA 95054  |  USA

Mobile: 925.699.8525  | www.paloaltonetworks.com<https://urldefense.com/v3/__https:/www.paloaltonetworks.com/__;!!A4F2R9G_pg!adEbxWQCG-NOTBOr77avGPme3N43pGXmKVJ-V34fZqk6Vzfq6gSejiUzIiA_Tnb4MKCPWvUV16yNeAw1sJQyq3IEGlrsn2S8MLI$>



[https://lh6.googleusercontent.com/xLri4pe_xrY16tHTAqfrpgQ1V9u2Ekq7WypYD4wMFFKLixymrU_3V_eWAW4jyri1sqAWQCaSqRqUG0-mckUsNA6io8t4808ASaZT5od5SzuHvvXrEJi26a8zh64RUT1CW1cXQoXj]<https://urldefense.com/v3/__https:/www.paloaltonetworks.com/prisma__;!!A4F2R9G_pg!adEbxWQCG-NOTBOr77avGPme3N43pGXmKVJ-V34fZqk6Vzfq6gSejiUzIiA_Tnb4MKCPWvUV16yNeAw1sJQyq3IEGlrsgMtsfw4$>


On Fri, Jun 24, 2022 at 10:06 AM Priyanka Aggarwal ***@***.******@***.***>> wrote:
Hi Sath,

Can you help  me  in figuring out what this notification for?

Best
Priyanka

From: Pubs-MV ***@***.******@***.***>>
Date: Friday, June 24, 2022 at 8:48 AM
To: PaloAltoNetworks/prisma-cloud-docs ***@***.******@***.***>>
Cc: Priyanka Aggarwal ***@***.******@***.***>>, Mention ***@***.******@***.***>>
Subject: Re: [PaloAltoNetworks/prisma-cloud-docs] Update install_single_container_defender.adoc (PR #371)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@Pubs-MV approved this pull request.

Thank you @snps-aggarw<https://urldefense.com/v3/__https:/github.com/snps-aggarw__;!!A4F2R9G_pg!dajk6vDt-7qCnuTUhnBUT5EpXWHKKn2Qk03rvOtc5ikXEj38hNHOChSk1ZZAmTnF4UJGvbY_17vTaa7vA0B6tdvc$>

**Pull request merged**
