### PR TITLE
Added support for .Net 6 AWS Lambda

### PR DESCRIPTION
**Pull request by avish9**

### CODE REVIEW

**Comment by Pubs-MV** [comment]
Hi @avish9 , is this for 22.06 or 22.12?

**Comment by avish9** [comment]
@Pubs-MV 22.06

**Comment by Pubs-MV** [comment]
@iansk , please merge this and republish 22.06 later this week.

**Comment by iansk** [comment]
Created a 22.06-specific PR and merged it instead. See https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/705

Closing this one unmerged.

**Pull request closed without merging**
