### PR TITLE
[CodeSec AG] Update with Projects 2.0 [RLP-102858]

### PR DESCRIPTION
**Pull request by anaghapamidi**
Summary of Changes:

Modified files:

- scan-monitor/monitor-fix-issues-in-scan/create-and-manage-code-category-views.adoc
- scan-monitor/monitor-fix-issues-in-scan/fix-issues-in-a-scan-result.adoc
- scan-monitor/monitor-fix-issues-in-scan/monitor-fix-issues-in-scan.adoc
- scan-monitor/software-composition-analysis/software-composition-analysis.adoc
- add-repository.png
- proj-10.png
- proj-11.png
- proj-12.png
- proj-13.png
- proj-14.png
- proj-15.png
- proj-16.png
- proj-17.png
- proj-19.png
- proj-20.png
- proj-24.png
- proj.png

Deleted files:
- proj-1.png
- proj-18.png
- proj-22.png
- suppress.png

Additional changes: 

- get-started/connect-your-repositories/add-aws-codebuild.adoc
   - Repository page screen update.
-  get-started/connect-your-repositories/connect-your-repositories.adoc
    - Fix artifactory link and update Repository screengrab.

### CODE REVIEW

**Comment by Pubs-MV** [comment]
can we merge this @anaghapamidi?

**Comment by anaghapamidi** [comment]
> can we merge this @anaghapamidi?

I'll require some more time Matangi.

**Comment by anaghapamidi** [comment]
Summary of changes for this [commit](https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/1216/commits/c36f5cfa2b9a76bd5bc41a76e7c194b4a994513d)

Modified Files:
- scan-monitor/drift-detection.adoc
- scan-monitor/monitor-fix-issues-in-scan/monitor-fix-issues-in-scan.adoc
- drift-1.png
- drift-2.png
- drift-3.png
- drift-4.png

Deleted Files:
- drift.png

**Comment by anaghapamidi** [comment]
Hi @Pubs-MV, this PR is ready for merge.

**Pull request merged**
