### PR TITLE
Add documentation on the type option for the create namespace command

### PR DESCRIPTION
**Pull request by rjain15**
Added documentation on the type option for the create namespace command. 

Currently, to get the doc, you have to specify 
apoctl api describe ns --full

### CODE REVIEW

**Review by arifulhuq — APPROVED** [review]

**Comment by arifulhuq** [comment]
@Pubs-MV please merge this doc PR from the field

**Comment by Pubs-MV** [comment]
Hi @rjain15 , I am unable to merge your changes. 
Can you please 
1. Get the latest from master.
2. Interactively rebase your branch using `git rebase -i master`

**Comment by Pubs-MV** [comment]
Merged the changes from the C:\GitHub\prisma-cloud-docs\cns\saas\admin_guide\apoctl\api.adoc in this PR165 to PR263 to prevent merge conflicts

**Comment by Pubs-MV** [comment]
Added changes to the k8s.adoc file to PR271.

**Pull request closed without merging**
