### PR TITLE
Update namespaces.adoc

### PR DESCRIPTION
**Pull request by jodydadescott**

### CODE REVIEW

**Review by rcaballeromx — COMMENTED** [review]
@jodydadescott Thank you for updating the content. I've edited it for clarity. Please review the descriptions because I had to clarify what the placeholders actually represent.

**Comment by Pubs-MV** [comment]
@rcaballeromx is this ready to merge?

**Comment by rcaballeromx** [comment]
@Pubs-MV No, I think that @jodydadescott should weigh in first to make sure that the tag examples are clear.

**Comment by Pubs-MV** [comment]
Microseg is announced for EOL, hence closing

**Pull request closed without merging**
