### PR TITLE
Updated openshift cis benchmark limitation

### PR DESCRIPTION
**Pull request by grevach**
Following a question raised by a customer

### CODE REVIEW

**Comment by grevach** [comment]
Hi @iansk @divyabhushan 
Matangi is out, can you please review the changes and push them? This is for a customer
Thanks!

**Comment by iansk** [comment]
@grevach Looks good to me. Merging this now. I'll publish it on Monday.

**Review by iansk — APPROVED** [review]

**Comment by grevach** [comment]
Thanks @iansk !
Please let me know once it is published, thanks!

**Comment by iansk** [comment]
@grevach This published and live

**Pull request merged**
