### PR TITLE
replace gcp1.png with 1.1

### PR DESCRIPTION
**Pull request by kdpanw**
Test for uploading image to replace gcp1.png without push access to the repo.
please replace gcp1.png with gcp1.1.png . I cannot do this as I do not have push access to this repo.
I have uploading the picture I'd like to use below.

### CODE REVIEW

**Comment by kdpanw** [comment]
The picture can be found by searching "Prisma Cloud - Kubernetes Security Defender" on the GCP marketplace, and then selecting the correct link with the associated title of "Prisma Cloud - Kubernetes Security Defender"
I cannot get the file to correctly upload to this PR currently.

**Comment by iansk** [comment]
Thanks @kdpanw. I've fixed the screenshot in this PR:

https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/131

This fix will go live a little later today.

**Comment by kdpanw** [comment]
Good work thank you @iansk !

**Pull request closed without merging**
