### PR TITLE
Create SaaS Console Logs.adoc as a new Topic

### PR DESCRIPTION
**Pull request by kdpanw**
There is currently no documentation for this endpoint but it is in fact required in some cases. Please review and consider this PR as we currently have a customer who we had to describe this to, but it is not documented. Thank you

CC: Cliff Shih.

### CODE REVIEW

**Comment by Pubs-MV** [comment]
Thank you for submitting a PR @kdpanw!  
You use api/v1/logs what should that point to in  the versioned endpoint list? I could not find it, in the API reference on https://prisma.pan.dev/api/cloud/cwpp

If it is supported, would users look for this in the API reference or better in the API workflow section on https://prisma.pan.dev/docs/cloud/cwpp/api-workflows/?

**Comment by kdpanw** [comment]
I will update this part with the information as soon as I collect it!

**Comment by kdpanw** [comment]
@Pubs-MV 

I believe that is the issue. That endpoint exists but it is not documented anywhere. I think it would look better in the API reference, with its own section perhaps. I suppose that is up to debate (I'm not entirely sure what would look better)

**Comment by iansk** [comment]
Thanks, @kdpanw. Very much appreciate your submission here. For now, our policy is that we only document versioned (i.e. supported) API endpoints. We strongly encourage customers to use versioned endpoints only because of the long term support for them, and the backwards compatibility guarantees. For the v1 endpoints, we don't guarantee any sort of stability. v1 endpoints can change from release to release, and that can impact a customer's operations. For that reason, we don't recommend customers build on v1 endpoints, and, don't document them.

That doesn't mean v1 endpoints are inaccessible. You can still invoke them. And our OpenAPI file contains the complete spec for them. We just don't offer docs for them.

**Pull request closed without merging**
