### PR TITLE
Added options for fields query parameters - GH#39340 and PCSUP-9836

### PR DESCRIPTION
**Pull request by ssugandh**
Hi @MayaShani,

I added the options for the field parameters for `api/v<VERSION>/hosts,get`. Can you please see and approve?

### CODE REVIEW

**Comment by Pubs-MV** [comment]
@MayaShani please review, so we can merge and publish.

**Comment by Pubs-MV** [comment]
@ssugandh @MayaShani says 'it seems right; if R&D provided the details it should be fine. Let me know if you need any other reviewers or we can merge it?

**Comment by ssugandh** [comment]
@Pubs-MV: We can merge it. It's just one approval is required. I can add you as a reviewer.

**Review by Pubs-MV — APPROVED** [review]
For the PCSUP-9836

**Pull request merged**
