### PR TITLE
[Do not merge][Compute API] #40680 - Add a v1 endpoint for the service provider

### PR DESCRIPTION
**Pull request by ssugandh**
Do not merge

### CODE REVIEW

**Comment by ssugandh** [comment]
After discussion with the team, this PR is not required to be merged.

**Comment by Pubs-MV** [comment]
can we close this Pr @ssugandh

**Comment by Pubs-MV** [comment]
is this still relevant or do you want to close this @ssugandh

**Comment by ssugandh** [comment]
@Pubs-MV : We can delete this PR if possible. This is not required.

**Pull request closed without merging**
