### PR TITLE
[Compute AG] Agentless Fixes Fire Drill

### PR DESCRIPTION
**Pull request by Pubs-MV**
Fixed hard coded URls, incorporated feedback from justin and hari, all the flurry of emails

### CODE REVIEW

**Review by Pubs-MV — COMMENTED** [review]
typos

**Comment by harisrini** [comment]
@Pubs-MV 
Screen Shot 2022-10-13 at 12 23 16 PM
1. Move the location
2. Since this is generic, remove JSON and leave it as 
Download the permission template from...

**Comment by harisrini** [comment]
@Aqsaxvv092 Post the link to the JSON and let @Pubs-MV add it directly to the note section in the above comment and also push it to the relevant Compute edition section too.

**Comment by Aqsaxvv092** [comment]
@harisrini I dont have the direct JSONs. The only ones we have are for Azure from Sean S. Can we use the ones you have for SaaS M&P but just for agentless section?

**Pull request merged**
