### PR TITLE
[CSPM RN] Updates to code sec look ahead

### PR DESCRIPTION
**Pull request by Pubs-MV**
RLP-87265 and no ticket for TF Run tasks

### CODE REVIEW

**Comment by Pubs-MV** [comment]
@Aishbn and @anaghapamidi FYI

**Comment by Aishbn** [comment]
@Pubs-MV - the above commits contain the latest LA update to go with 22.12.1.

**Comment by Aishbn** [comment]
@Pubs-MV - added another one to the CSPM LA to go with 22.12.1

**Comment by Aishbn** [comment]
@Pubs-MV - the above commits contain the latest CSPM LA updates to go with 22.12.1.

**Review by Pubs-MV — COMMENTED** [review]
adding this known issue to the [Prisma Cloud known issues](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-release-notes/prisma-cloud-release-information/known-issues).

**Pull request merged**
