### PR TITLE
[Code Sec Policy Reference] Policies update

### PR DESCRIPTION
**Pull request by anaghapamidi**
Summary of changes:

- Remove `,` from code blocks.

### CODE REVIEW

**Comment by anaghapamidi** [comment]
Summary of changes:

- Remove `, ` from code blocks. (80 files fixed)

**Comment by anaghapamidi** [comment]
Summary of changes:

Remove `, ` from code blocks. (94 files fixed)

**Comment by anaghapamidi** [comment]
Summary of changes:

- Remove` , ` from code blocks. (200 files fixed).
- Add missing Policy Details.
- Remove double lines after code blocks.
- Format files.

**Comment by anaghapamidi** [comment]
Summary of changes:

- Remove `, `from code blocks. (104 files fixed).

**Comment by anaghapamidi** [comment]
Summary of changes:

Modified files:
- book.yml
-  build-integrity-policies/github-actions-policies/github-actions-contain-workflow-dispatch-input-parameters.adoc

**Review by manukumar6 — APPROVED** [review]

**Pull request merged**
