### PR TITLE
Circleci updates

### PR DESCRIPTION
**Pull request by anaghapamidi**
Hi @Pubs-MV and @iansk I have created another branch with just the circelci updates. 
Just this time around I have branched this from my last commit https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/176 in the older code-sec branch, as I did not want to loose out on the changes there. 
I hope this is fine and @Pubs-MV you are not seeing a whole list of files. My next commit will be branched from the master following the standard procedure.

### CODE REVIEW

**Comment by Pubs-MV** [comment]
> Hi @Pubs-MV and @iansk I have created another branch with just the circelci updates. Just this time around I have branched this from my last commit #176 in the older code-sec branch, as I did not want to loose out on the changes there. I hope this is fine and @Pubs-MV you are not seeing a whole list of files. My next commit will be branched from the master following the standard procedure.

Hey @anaghapamidi, this PR shows that you still have 111 files that have changed. Would you be able to save the updated circleci adoc file  to your desktop and keep the images too. Then delete this PR, get latest and replace the circleci file with the content saved on your desktop, then add the images to a new with the adoc file and images.

@iansk is this the right workflow or is there a better way to do this?

**Comment by iansk** [comment]
@Pubs-MV @anaghapamidi Yes, that's a good workflow.

**Comment by ginguyen** [comment]
[code-security/_graphics/circleci-3.png](https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/188/files#diff-fef9ffc8f743bc7cecbb718635f063d5a3cc7f801e2dff561310edd30a296cb4) looks outdated, let's wait for BC team to reply with their suggestion (they may need to fix the code text on their end).  Other than that, CircleCI material looks good and verified as technically correct.

**Review by Pubs-MV — COMMENTED** [review]
Can you close this PR now that ian created PR 191 with the required changes, @anaghapamidi ?

**Pull request closed without merging**
