### PR TITLE
Updates for CircleCi and AWS Code Build

### PR DESCRIPTION
**Pull request by anaghapamidi**

### CODE REVIEW

**Comment by Pubs-MV** [comment]
Hey @anaghapamidi , something is wrong here. Why are there so many files in this PR? 
Can you please close this out and only submit the last two files that you changed recently in a new PR? 

@iansk is that the correct action here?

**Comment by iansk** [comment]
@Pubs-MV Yes, that's the right action. If I recall, this is an old branch (`code-sec`). @anaghapamidi, are you reusing an old branch for new work?

Once a branch is merged here on GitHub, you should delete that branch on your local machine too. When you're starting new work, checkout master, and then create a new branch from master so that you're working with the latest source. Assuming you deleted the old branch, you can create a new branch also named `code-sec` if you like. Or you can name it something more specific to the issue you're working on.

**Comment by anaghapamidi** [comment]
> @Pubs-MV Yes, that's the right action. If I recall, this is an old branch (`code-sec`). @anaghapamidi, are you reusing an old branch for new work?
> 
> Once a branch is merged here on GitHub, you should delete that branch on your local machine too. When you're starting new work, checkout master, and then create a new branch from master so that you're working with the latest source. Assuming you deleted the old branch, you can create a new branch also named `code-sec` if you like. Or you can name it something more specific to the issue you're working on.

Hi @Pubs-MV let me re-commit. @iansk you are right I am reusing the branch. I will fix this. Henceforth, I will follow this method to commit.

**Comment by Pubs-MV** [comment]
closing this request because we submitted https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/191 with the correct changes.

**Pull request closed without merging**
